//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN:VCALENDAR
        ///PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
        ///VERSION:2.0
        ///BEGIN:VTIMEZONE
        ///TZID:Europe/Rome
        ///TZURL:http://tzurl.org/zoneinfo/Europe/Rome
        ///X-LIC-LOCATION:Europe/Rome
        ///BEGIN:DAYLIGHT
        ///TZOFFSETFROM:+0100
        ///TZOFFSETTO:+0200
        ///TZNAME:CEST
        ///DTSTART:19700329T020000
        ///RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
        ///END:DAYLIGHT
        ///BEGIN:STANDARD
        ///TZOFFSETFROM:+0200
        ///TZOFFSETTO:+0100
        ///TZNAME:CET
        ///DTSTART:19701025T030000
        ///RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
        ///END:STANDARD
        ///END:VTIMEZONE
        ///BEGIN:VEVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AndroidPut {
            get {
                return ResourceManager.GetString("AndroidPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN:VCALENDAR
        ///PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
        ///VERSION:2.0
        ///BEGIN:VTIMEZONE
        ///TZID:Europe/Berlin
        ///BEGIN:DAYLIGHT
        ///TZOFFSETFROM:+0100
        ///TZOFFSETTO:+0200
        ///TZNAME:CEST
        ///DTSTART:19700329T020000
        ///RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
        ///END:DAYLIGHT
        ///BEGIN:STANDARD
        ///TZOFFSETFROM:+0200
        ///TZOFFSETTO:+0100
        ///TZNAME:CET
        ///DTSTART:19701025T030000
        ///RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
        ///END:STANDARD
        ///END:VTIMEZONE
        ///BEGIN:VEVENT
        ///CREATED:20151007T103938Z
        ///LAST-MODIFIED:20151007T103946Z
        ///DTSTAMP:2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PutRecurring {
            get {
                return ResourceManager.GetString("PutRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN:VCALENDAR
        ///PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
        ///VERSION:2.0
        ///BEGIN:VEVENT
        ///LAST-MODIFIED:20151007T111607Z
        ///DTSTAMP:20151007T111607Z
        ///UID:8ac339c8-fa1c-4d23-9ee9-8b16e303c13d
        ///SUMMARY:rec3
        ///RRULE:FREQ=DAILY;COUNT=8;INTERVAL=5
        ///EXDATE:20151013T140000
        ///DTSTART:20151008T140000
        ///DTEND:20151008T150000
        ///SEQUENCE:1
        ///X-MOZ-GENERATION:1
        ///END:VEVENT
        ///END:VCALENDAR.
        /// </summary>
        internal static string PutWithEXDATE {
            get {
                return ResourceManager.GetString("PutWithEXDATE", resourceCulture);
            }
        }
    }
}
